# Generated by Django 2.1.7 on 2019-05-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('edu_course', '0002_useremail'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('to_user', models.ManyToManyField(to='edu_course.UserEmail')),
            ],
            options={
                'verbose_name': '发送邮件',
                'verbose_name_plural': '发送邮件',
            },
        ),
    ]
